### PR TITLE
docs-build github pages publish

### PR DESCRIPTION
**Pull request by briantist**
## Description

- Simplify the PR validate workflow
  - https://github.com/ansible-community/github-docs-build/pull/45
- Add GitHub Pages publishing so we can have a rendered docsite 🎉 
  - https://github.com/ansible-community/github-docs-build/pull/44

## How Has This Been Tested?

Testing done on a fork I had of another collection, and testing done on my collection as well (https://github.com/ansible-collections/community.hashi_vault/pull/261).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) - Fixes #
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read/followed the [**CONTRIBUTING**](https://github.com/LowlyDBA/lowlydba.sqlserver/blob/main/.github/CONTRIBUTING.md) document.
- [x] I have read/followed the [PR Quick Start Guide](https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst)  # TODO: update with link to published doc
- [x] I have added tests to cover my changes or they are N/A.
- [ ] New module options/parameters include a [`version_added` property](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fields).

### CODE REVIEW

**Comment by briantist** [comment]
As usual, the `pull_request_target` workflows can't be tested easily without opening new PRs to the PR branch, but I have tested elsewhere.

**Comment by lowlydba** [comment]
Pages enabled ✅

**Comment by lowlydba** [comment]
Interestingly it seems to [fail](https://github.com/lowlydba/lowlydba.sqlserver/runs/6249053295?check_suite_focus=true#step:4:18) without a `/docs` dir even though it isn't really used in the final product 🤔

**Comment by briantist** [comment]
> Interestingly it seems to [fail](https://github.com/lowlydba/lowlydba.sqlserver/runs/6249053295?check_suite_focus=true#step:4:18) without a `/docs` dir even though it isn't really used in the final product 🤔

ah no that error isn't actually related to the docs dir, it's about it trying to run jekyll against a site that's not a jekyll project. I think docs is just the dir used in the built-in workflow for it.

The next build worked great!
https://lowlydba.github.io/lowlydba.sqlserver/branch/main/

**Comment by briantist** [comment]
The list of plugins on the README can now be replaced with a direct link to:
https://ansible-collections.github.io/community.hashi_vault/branch/main/collections/community/hashi_vault/index.html#plugin-index

Or each individual one could still point to the individual pages, but will require manual updating that way.

**Pull request merged**
