### PR TITLE
fix: use local file for sp_whoisactive install

### PR DESCRIPTION
**Pull request by Joey40**
## Description
Use a local file to install sp_whoisactive during integration tests to avoid 403 error

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) - Fixes #
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read/followed the [**CONTRIBUTING**](https://github.com/LowlyDBA/lowlydba.sqlserver/blob/main/CONTRIBUTING.md) document.
- [x] I have read/followed the [PR Quick Start Guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html)
- [x] I have added tests to cover my changes or they are N/A.
- [x] I have added a [changelog fragment](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst#changelog-fragment-categories) describing the changes.
- [ ] New module options/parameters include a [`version_added` property](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fields).

### CODE REVIEW

**Comment by lowlydba** [comment]
I'm game to add this as an additional integration test, but want to keep the download option in the tests for sure to get proper end-to-end coverage since that is likely how most people will be using it. 

I don't see any issues reported in dbatools about this, or incidents for Github.com so am going to guess it may be transient and will resolve itself soon. It hasn't been a problem before.

**Comment by Joey40** [comment]
Fair enough.  I'll revert the changes, and add the local file as an additional test.

**Comment by lowlydba** [comment]
> Fair enough. I'll revert the changes, and add the local file as an additional test.

Thanks! I also opened a Github support issue to see if this can get resolved faster that way.

**Comment by lowlydba** [comment]
This hasn't been a problem for a while, so perhaps how the VMs are allocated, or API throttling has been changed on GitHub's side. I'm going to close for now but feel free to re-open and continue work if it becomes an issue again.

**Pull request closed without merging**
