### PR TITLE
first pass at windows integration

### PR DESCRIPTION
**Pull request by briantist**
## Description
Trying out integration against Windows (WIP)

Current state of this: there was a lot more to it than I expected, here's a bunch of notes in no particular order:

- `ansible-test windows-integration` will only use targets that contain `windows/` in their `aliases` file
- `ansible-test integration` will only use targets that _do not_ contain `windows/` in their `aliases` file
- my current thinking around that is that we'll add `win_<target>` targets, and those will contain `windows/` in their `aliases`
  - those targets will by and large just depend on the other one rather than have their own tasks, however this also makes it possible to add additional tasks that only apply to Windows, if there is such a thing (maybe something around Windows auth for example)
  - this is current;y demonstrated in the PR with the `database` (and now `win_database`) targets
- `setup_` targets _also_ need to contain `windows/` in their `aliases` so some special stuff is needed there as well
- we need to use the pwsh runner only conditionally, or set it in a different place, for tests to support for both Windows and non-Windows; I made some changes to that effect so far, but it's worth revisiting how we want to do that going forward
- I bent over backwards a little to have the `setup_sqlserver` and `setup_win_sqlserver` share vars and such but it's... meh, it might be cleaner to duplicate instead, not sure yet
- Windows tests will be take a long time... 
  - it takes around 30s to enable the runner for PS remoting
  - nearly 5 minutes to install SQL server
  - around 2m to setup WSL 
  - another minute or so to install Ansible
  - Also the setup role that installs `dbatools` takes an unusually long time to complete against the Windows host and I don't know why; I think it makes sense to keep the (new) Windows setup role (thinking outside the CI here), but I want to try pre-installing `dbatools` directly from the Windows side; if that's much faster, then when we try to do it in the setup role, it should  find that it's installed and not take so long 🤞
  - So after all this (about 10m) we can start running actual tests, which are a bit slower to run but not so bad; it's just a lot of delay getting there
- The big advantages of testing against Windows are:
  - that we actually test against it! (most people will probably be using these modules on Windows I presume)
  - and also that we get real coverage, which can be seen from the project coverage "dropping" now that it's actually getting real data; but it's a good thing, and we get to see the coverage reports and what functionality we don't have tests for yet, so that's cool
- This is a separate workflow for a few reasons:
  - there's so many extra and differing steps, it didn't seem to make sense to add tons of conditionals all over the place in the other workflow
  - given the amount jank, if we start hitting problems it's easy to blanket disable the entire workflow from the GH UI without having to push any changes.
- Since we can't use service containers on non-ubuntu runners 😢 we're back to that SQL action to install
  - need a slightly different integration config as a result
  - if we wanted to, I think we could change the linux invocations to stop using the ansible-test containers and instead run directly on the runner (they'd probably be faster too, but may take a little more steps to set up), and we could go back to using the action instead (which is going to set up a container anyway, the difference is no longer needing to customize the docker network)
- there's a lot left to clean up and fix, and decisions to be made on some of this

## How Has This Been Tested?
_"It **IS** the tests, Frylock!"_

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) - Fixes #
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read/followed the [**CONTRIBUTING**](https://github.com/LowlyDBA/lowlydba.sqlserver/blob/main/.github/CONTRIBUTING.md) document.
- [x] I have read/followed the [PR Quick Start Guide](https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst)  # TODO: update with link to published doc
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by lowlydba** [comment]
Amazing! So cool to see _actual_ code coverage for the powershell 😎 

I need to spend a little time groking all the files, but at a high level I like the approach and agree its a good path forward. 

Since we're working with pretty high CI times now, we might benefit from adding in Chrissy's other GH Action for [module caching](https://github.com/marketplace/actions/powershell-module-cache) to get what's needed faster.

**Comment by briantist** [comment]
> Amazing! So cool to see _actual_ code coverage for the powershell 😎
> 
> I need to spend a little time groking all the files, but at a high level I like the approach and agree its a good path forward.
> 
> Might be useful to use https://github.com/marketplace/actions/powershell-module-cache to cache the powershell modules in the windows runner.

ooo that looks promising but I'm looking at the CI run, and I think the problem we're going to run into is that the module seems to be installed per-user, and we're using a new user to connect from WSL to Windows, so it won't actually be available in the user we need. Maybe we should put a PR in for that action to customize the user; should be an easy change.

**Comment by lowlydba** [comment]
Seems like we're now hitting a [known issue with the underlying cache action](https://github.com/actions/cache/issues/198)...

**Comment by lowlydba** [comment]
This should be resolved via https://github.com/potatoqualitee/psmodulecache/pull/20

**Comment by lowlydba** [comment]
With the ongoing subtleties of the caching, don't want to hold this up for too long. I'm happy to merge in its current state to unblock rolling out the windows stuff to the rest of the modules

**Review by lowlydba — DISMISSED** [review]

**Comment by briantist** [comment]
> With the ongoing subtleties of the caching, don't want to hold this up for too long. I'm happy to merge in its current state to unblock rolling out the windows stuff to the rest of the modules

There's still a bunch of work to be done to get this mergeable imo, but yeah we don't have to wait on caching.

**Comment by lowlydba** [comment]
> > With the ongoing subtleties of the caching, don't want to hold this up for too long. I'm happy to merge in its current state to unblock rolling out the windows stuff to the rest of the modules
> 
> There's still a bunch of work to be done to get this mergeable imo, but yeah we don't have to wait on caching.

Aside from cleaning up the ci yml, what did you have in mind?

**Comment by briantist** [comment]
> > > With the ongoing subtleties of the caching, don't want to hold this up for too long. I'm happy to merge in its current state to unblock rolling out the windows stuff to the rest of the modules
> > 
> > 
> > There's still a bunch of work to be done to get this mergeable imo, but yeah we don't have to wait on caching.
> 
> Aside from cleaning up the ci yml, what did you have in mind?

There's little stuff, like perhaps disentangling the dbatools install roles so that they don't depend on each other (add a little duplication for much more simplicity), but the big thing needed is to refactor all the targets; I've only done that for a single module here (`database`). That involves:
- creating `win_` targets for each one that (probably only) call the "original"
- removing the application of the shell/connection variables from the "original"
- running through the tests for each one and fixing any latent issues that might be present that make the tests only work on or the other platform
- same as above, but fixing legitimate module issues that prevent them from working cross-platform
- adding platform-specific tests that may be needed in a way that they don't run on the other platform (this is a little harder because there will be no failing test to fix, it's just us recognizing when a certain thing should be tested in a way that's specific to a platform, hopefully these are rare
  - this can also be done separately, but I bring it up because without a failing test or a missed coverage line, it will be easy to overlook these when you're not in the middle of working on tests for a given module

**Comment by lowlydba** [comment]
Ah, gotcha. I was envisioning handling most of that in one (or more) subsequent PRs due to the size of the work. That's probably the major barrier before a v0.1 / setting it up in Galaxy.

I only have one more module to port over (agent_job_steps) and then want to add a Login one, then plan to cut off new module development until everything is in working order with good test coverage.

Since the current integration tests are just MVPs, I assumed I'd be reworking them once the code coverage was available.  

> adding platform-specific tests that may be needed in a way that they don't run on the other platform (this is a little harder because there will be no failing test to fix, it's just us recognizing when a certain thing should be tested in a way that's specific to a platform, hopefully these are rare

I'm hoping for now (and something proximate to v0.1) this is a non-issue since I'm mostly targeting instance level configuration which should all be platform agnostic, outside of perhaps some pwsh features I may be guilty of using (which should be an obvious error)

**Comment by briantist** [comment]
> Ah, gotcha. I was envisioning handling most of that in one (or more) subsequent PRs due to the size of the work. That's probably the major barrier before a v0.1 / setting it up in Galaxy.
> 
> I only have one more module to port over (agent_job_steps) and then want to add a Login one, then plan to cut off new module development until everything is in working order with good test coverage.
> 
> Since the current integration tests are just MVPs, I assumed I'd be reworking them once the code coverage was available.
> 

I mostly lean toward doing it all in this PR because of unknowns: the path forward I've laid here seems ok, maybe after converting a few more roles the process will need rethinking. 

But that doesn't mean that can't be done in subsequent PRs too, so I'll leave it to your preference, good chance I'm just being lazy and/or overly cautious.

Re: "the size of the work" if it goes smoothly, it's mostly just moving lines around and making some new folders and files, but still a good fit for new PRs if you prefer that!

> > adding platform-specific tests that may be needed in a way that they don't run on the other platform (this is a little harder because there will be no failing test to fix, it's just us recognizing when a certain thing should be tested in a way that's specific to a platform, hopefully these are rare
> 
> I'm hoping for now (and something proximate to v0.1) this is a non-issue since I'm mostly targeting instance level configuration which should all be platform agnostic, outside of perhaps some pwsh features I may be guilty of using (which should be an obvious error)

I agree, that isn't likely to be needed in the vast majority of cases.

**Comment by lowlydba** [comment]
Seems fair. I'll probably add some commits soon to convert other ones, then.

**Comment by lowlydba** [comment]
Close to working right off the bat...banging my head against the wall with the nested collections from Resource Gov though. Interestingly it seems to work in Core just fine 🤔 

> ok: [runner] => {
>     "changed": false,
>     "data": {
>         "ClassifierFunction": "",
>         "ComputerName": "fv-az28-443",
>         "Enabled": true,
>         "ExternalResourcePools": "default",
>         "InstanceName": "MSSQLSERVER",
>         "MaxOutstandingIOPerVolume": 0,
>         "ReconfigurePending": false,
>         "ResourcePools": {
>             "Count": 2,
>             "value": [
>                 "default",
>                 "internal"
>             ]
>         },
>         "SqlInstance": "fv-az28-443"
>     },
>     "invocation": {
>         "module_args": {
>             "classifier_function": null,
>             "enabled": true,
>             "sql_instance": "localhost",
>             "sql_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
>             "sql_username": "sa"
>         }
>     }
> }
> Read vars_file 'integration_config.yml'
> 
> TASK [resource_governor : assert] **********************************************
> task path: /mnt/d/a/lowlydba.sqlserver/lowlydba.sqlserver/ansible_collections/lowlydba/sqlserver/tests/output/.tmp/integration/win_resource_governor-t96wgflc-ÅÑŚÌβŁÈ/tests/integration/targets/resource_governor/tasks/main.yml:16
> fatal: [runner]: FAILED! => {
>     "assertion": "'default' in result.data.ResourcePools",
>     "changed": false,
>     "evaluated_to": false,
>     "msg": "Assertion failed"
> }
>

**Comment by briantist** [comment]
> Close to working right off the bat...banging my head against the wall with the nested collections from Resource Gov though. Interestingly it seems to work in Core just fine 🤔
> 
> > "ResourcePools": {
> > "Count": 2,
> > "value": [
> > "default",
> > "internal"
> > ]

Ah! I know this issue, see:
https://github.com/ansible-collections/community.windows/blob/09c6aed12aea1de872ac072aa0aa0b63a7cc5484/plugins/modules/win_psmodule_info.ps1#L19-L22

**Comment by lowlydba** [comment]
Wow, thanks. I don't want to think about how long that would've taken me to find or figure out  😭

**Comment by briantist** [comment]
yeah.. writing `win_psmodule_info` was a whole rollercoaster of serialization issues.

I might have a way to also get rid of the windows-specific `integration_config.yml` too, that was another thing I wanted to clean up, will give that a try

**Comment by briantist** [comment]
There's something wrong with `agent_job`:

```
TASK [agent_job : Create agent job] ********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 142
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Exception calling \"FailJson\" with \"2\" argument(s): \"urn could not be resolved at level OleDbProviderSetting.\""}
```

In both the Linux and Windows environments, this failure happens, but because we use `ansible-test --retry-on-error`  it runs again, and then it always succeeds the second time.

Will not have a chance to look into it tonight, but the re-attempt will slow down tests slightly.

---

Single `integration_config.yml` has been achieved via a `hosts` file entry 🎉 

---

I split up the Windows tests into testing groups, because they're so slow and because we were not fully using the GHA capacity.

We can't do much else about setup times which are close to 10m, but the integration tests themselves were taking 11-12m minutes for all current modules.

So I figured if we group them, matrix them, and run 2 more sets in parallel, we could at least cut down total test time. I made 3 groups, and groups 1 & 2 have 4 targets each while group 3 has the remaining 3 targets.

The results are not quite what I expected; each group is taking 5-6m each. So it's still possibly cutting ~5m or so from the total run time, in theory (in practice more like 1-2m 😕).

Fixing `agent_job` might tip that to be slightly better... some of the reason for the less dramatic change might be due to the setup target, since it only runs once, its impact is less, the more targets you run. 

Perhaps that will improve when the caching for `dbatools` is working.

Anyway, the grouping is entirely in commit e308e8c so if you're not feeling that you can revert it easily.

I also just went alphabetical in assigning targets to groups, you could assign them more meaningfully if you want, or better group them to evenly distribute expected run times for the tests.

I wouldn't go more than 3 groups at the moment though, because the concurrency limit for GHA is 20 jobs running, we have 8 running in the Linux tests (4x sanity, 4x integration), and now 12 in Windows (4 ansible x 3 groups), and because of our exceptionally large setup time, any queuing will quickly eat into any time savings to be had by splitting on groups.

**Comment by lowlydba** [comment]
Awesome!

The agent thing is weird, I'm unable to repro locally. I'm wondering if it's similar to [this](https://github.com/lowlydba/dba-multitool/pull/178) at all, where the first time querying the feature (sensitivity classifications) there is some undocumented startup process that makes it lag a bit and makes a query fail if it happens too fast. Maybe the same thing for Agent related tables on a fresh installation. 

I can try adding a task in the setup phase to 'initialize' it and see if that makes any difference.

**Comment by lowlydba** [comment]
agent_job is now succeeding on the first go, it looks like its a bug with SMO/Agent reporting essentially stale/out of date data. Fixed via 780183b2df5c9651e2b99f751102ae03b3a48fca and 83e92f41550cfdbc43b06d435cc0607f00d6abee where the newly created job is manually fetched (effectively adding a slight delay) and the category is pre-created.

Since the agent runs as its own service, I recall there being some timers in the background that run to make updates to the objects that sometimes require manual refreshes or delays - I've mostly run in this with job schedules. Probably made worse by the underpowered runners.

**Comment by briantist** [comment]
hm, frustrating, I wonder if there's a way to make the module more resilient from within, maybe that condition can be checked for?

At the least, might be worth adding something to the `notes:` field in the module documentation, and maybe showing a better error message in the module if possible.

---

Otherwise I'm ready to merge when you are, and to continue with anything else in other PRs, except that I am wondering if we should keep the grouped jobs, and if so, should we cut it down to 2 groups instead of 3 due to concurrency concerns?

For example I was thinking of introducing a docs build PR (it won't have the publish step yet, so it will be more about verification that docs build cleanly, with publishing coming later), but those will either run first, delaying some of the integration tests (really bad because of their setup times) or run last, which will be bad for feedback on the docs jobs which run relatively quickly.

**Comment by lowlydba** [comment]
2 groups makes sense to me - easier to manage and probably only worth revisiting once there are many more commands (a while away).

**Review by lowlydba — DISMISSED** [review]
LGTM!

**Review by lowlydba — APPROVED** [review]

**Pull request merged**
