### PR TITLE
experimental alwayson modules

### PR DESCRIPTION
**Pull request by lowlydba**
Not sure how easy or hard this will be to get proper testing running for AlwaysOn AG related modules. I don't have a test lab with Windows Server so there may be a lot of trial and error on here with clusterless AGs and seeing how far we can get in Linux as well.

`hadr` won't apply to Linux and will be needed to get any future AG tests working on Windows.

Modules working:
* ✅  hadr
* ✅   availability_group

### CODE REVIEW

**Comment by lowlydba** [comment]
The behavior is confusing.

```
TASK [win_hadr : Enable hadr] **************************************************
changed: [runner] => {"changed": true, "data": {"ComputerName": "sqlserver", "InstanceName": "MSSQLSERVER", "IsHadrEnabled": true, "SqlInstance": "sqlserver"}}

TASK [win_hadr : assert] *******************************************************
ok: [runner] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [win_hadr : Disable hadr] *************************************************
ok: [runner] => {"changed": false, "data": {"ComputerName": "fv-az28-824", "InstanceName": "MSSQLSERVER", "IsHadrEnabled": false, "SqlInstance": "fv-az28-824"}}

TASK [win_hadr : assert] *******************************************************
ok: [runner] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [win_hadr : Enable hadr] **************************************************
changed: [runner] => {"changed": true, "data": {"ComputerName": "sqlserver", "InstanceName": "MSSQLSERVER", "IsHadrEnabled": true, "SqlInstance": "sqlserver"}}

TASK [win_hadr : assert] *******************************************************
ok: [runner] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [win_hadr : Disable hadr] *************************************************
ok: [runner] => {"changed": false, "data": {"ComputerName": "fv-az28-824", "InstanceName": "MSSQLSERVER", "IsHadrEnabled": false, "SqlInstance": "fv-az28-824"}}

TASK [win_hadr : assert] *******************************************************
ok: [runner] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [win_hadr : Checkmode enable hadr] ****************************************
changed: [runner] => {"changed": true, "data": {"ComputerName": "sqlserver", "InstanceName": "MSSQLSERVER", "IsHadrEnabled": true, "SqlInstance": "sqlserver"}}

TASK [win_hadr : assert] *******************************************************
ok: [runner] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [win_hadr : Verify checkmode works] ***************************************
ok: [runner] => {"changed": false, "data": {"ComputerName": "fv-az28-824", "InstanceName": "MSSQLSERVER", "IsHadrEnabled": false, "SqlInstance": "fv-az28-824"}}

TASK [win_hadr : assert] *******************************************************
ok: [runner] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
runner                     : ok=12   changed=3    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

**Comment by lowlydba** [comment]
At least some weirdness related to https://github.com/dataplat/dbatools/issues/8295

**Comment by lowlydba** [comment]
Key element to get hadr enabled working was enabling winrm on the runner.

**Comment by lowlydba** [comment]
AG creation is failing with this - out of ideas currently.

> Configuring Availability Group failed: Windows NT user or group 'NT AUTHORITY\\NETWORKSERVICE' not found. Check the name again.

**Comment by briantist** [comment]
> AG creation is failing with this - out of ideas currently.
> 
> > Configuring Availability Group failed: Windows NT user or group 'NT AUTHORITY\NETWORKSERVICE' not found. Check the name again.

Given that that account is a known SID, and that it authenticates on the network differently, I wonder if it's better to create a new local user instead. NetworkService isn't privileged on the local machine so any standard user should be basically equivalent.. but this might require separate/special runners with SQL server configured differently, not sure.

I assume that with no AD in the picture, you'll also need to use certs for auth between nodes? AG is going to be hard to test in GHA for sure.

**Comment by lowlydba** [comment]
Looks like switching service accounts got it to progress further before hitting another error 🤞🏻 

> I assume that with no AD in the picture, you'll also need to use certs for auth between nodes? AG is going to be hard to test in GHA for sure.

Yeah, not even _thinking_ about that yet. The majority of stuff I can test on a single-node AG (I hope)

**Comment by lowlydba** [comment]
😠 Alright, so clearly some sort of prompt is happening, but the full message seems to be truncated. I'm out of ideas on how to get more details.

>A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: 

 I was able to test this as closely to possibly locally, _and it works fine_. @briantist Any ideas?

**Comment by briantist** [comment]
> 😠 Alright, so clearly some sort of prompt is happening, but the full message seems to be truncated. I'm out of ideas on how to get more details.
> 
> > A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message:
> 
> The dbatools source is passing down `Exception.InnerException.InnerException.Message` - not clear to me if that is where the truncation is happening or not.
> 
> I was able to test this locally, _and it works fine_. @briantist Any ideas? I really don't want to set all of this up in Appveyor just to get the ability to RDP and live troubleshoot to a Windows host, but that's all I can think of at this point.

The [`ConfirmImpact` is set to high on this command](https://github.com/dataplat/dbatools/blob/master/functions/New-DbaAvailabilityGroup.ps1#L263) so I think you need to need to call it with `-Confirm:$false`.

If that doesn't do it, you can try to troubleshoot with [something like this](https://github.com/cationx/GitHub-Action-RDP), but hopefully it doesn't come to that.

**Comment by lowlydba** [comment]
> The [`ConfirmImpact` is set to high on this command](https://github.com/dataplat/dbatools/blob/master/functions/New-DbaAvailabilityGroup.ps1#L263) so I think you need to need to call it with `-Confirm:$false`.

I had that originally, then switched to 

```
$PSDefaultParameterValues = @{ "*:EnableException" = $true; "*:Confirm" = $false }
```

in the hopes it might work better for child function calls, but no luck. 

Neat RDP action! Seems like the next step :(

**Comment by lowlydba** [comment]
✅ 🎉

**Pull request merged**
